from __future__ import annotations

from datetime import UTC, datetime
from io import BytesIO
from typing import Any

from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    KeepTogether,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from core.export.base import EXPORTERS, ExportPayload, ExportResult, IExporter
from core.export.response_render import (
    format_response_text,
    iter_sub_panels,
    response_chart_spec,
    response_scatter_spec,
    response_table_matrix,
    sanitize_filename,
)

BRAND_PRIMARY = colors.HexColor("#2563eb")
BRAND_DARK = colors.HexColor("#0f172a")
BRAND_MUTED = colors.HexColor("#64748b")
BRAND_BORDER = colors.HexColor("#e2e8f0")
BRAND_SURFACE = colors.HexColor("#f8fafc")
CHART_PALETTE = [
    colors.HexColor("#2563eb"),
    colors.HexColor("#0ea5e9"),
    colors.HexColor("#22c55e"),
    colors.HexColor("#f59e0b"),
    colors.HexColor("#ef4444"),
    colors.HexColor("#a855f7"),
    colors.HexColor("#14b8a6"),
]

PAGE_W, PAGE_H = letter
MARGIN = 0.65 * inch


class _BrandedCanvas(pdfcanvas.Canvas):
    """Canvas that buffers pages so the footer can render 'Page X of N'."""

    def __init__(self, *args: Any, doc_title: str = "InsightIQ", **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_states: list[dict[str, Any]] = []
        self._doc_title = doc_title

    def showPage(self) -> None:  # noqa: N802 - reportlab API
        self._saved_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        total = len(self._saved_states)
        for state in self._saved_states:
            self.__dict__.update(state)
            if total > 1 and self._pageNumber > 1:
                self._draw_chrome(self._pageNumber, total)
            super().showPage()
        super().save()

    def _draw_chrome(self, page_number: int, total_pages: int) -> None:
        self.saveState()
        self.setStrokeColor(BRAND_BORDER)
        self.setLineWidth(0.6)
        self.line(MARGIN, PAGE_H - 0.5 * inch, PAGE_W - MARGIN, PAGE_H - 0.5 * inch)
        self.setFont("Helvetica-Bold", 8.5)
        self.setFillColor(BRAND_PRIMARY)
        self.drawString(MARGIN, PAGE_H - 0.4 * inch, "InsightIQ")
        self.setFont("Helvetica", 8.5)
        self.setFillColor(BRAND_MUTED)
        self.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.4 * inch, self._doc_title[:70])

        self.line(MARGIN, 0.45 * inch, PAGE_W - MARGIN, 0.45 * inch)
        self.setFont("Helvetica", 8)
        self.setFillColor(BRAND_MUTED)
        self.drawString(MARGIN, 0.3 * inch, "Generated by InsightIQ \u2022 Confidential")
        self.drawRightString(PAGE_W - MARGIN, 0.3 * inch, f"Page {page_number - 1} of {total_pages - 1}")
        self.restoreState()


@EXPORTERS.register("pdf")
class PdfExporter(IExporter):
    async def export(self, *, payload: ExportPayload) -> ExportResult:
        buffer = BytesIO()
        doc = BaseDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=1.0 * inch,
            bottomMargin=0.75 * inch,
            title=payload.title,
            author="InsightIQ",
        )
        content_frame = Frame(MARGIN, doc.bottomMargin, PAGE_W - 2 * MARGIN, doc.height, id="content")
        cover_frame = Frame(MARGIN, doc.bottomMargin, PAGE_W - 2 * MARGIN, doc.height, id="cover")
        doc.addPageTemplates(
            [
                PageTemplate(id="cover", frames=[cover_frame]),
                PageTemplate(id="content", frames=[content_frame]),
            ]
        )

        styles = getSampleStyleSheet()
        body_style = ParagraphStyle(
            "Body", parent=styles["Normal"], fontName="Helvetica", fontSize=10, leading=14, textColor=BRAND_DARK
        )
        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=BRAND_DARK,
            spaceBefore=6,
            spaceAfter=8,
        )

        story: list[Any] = _cover_story(payload)
        story.append(NextPageTemplate("content"))
        story.append(PageBreak())

        if payload.content_type == "conversation":
            for msg in payload.data.get("messages", []):
                role = str(msg.get("role", "user")).upper()
                content = str(msg.get("content", ""))
                block: list[Any] = [Paragraph(role, heading_style), *_paragraph_lines(content, body_style)]
                story.append(KeepTogether(block))
                story.append(Spacer(1, 12))
        else:
            for card in payload.data.get("cards", []):
                title = str(card.get("title", "Card"))
                response = card.get("response") or {}
                if not response and card.get("summary"):
                    response = {"response_type": "explanation", "data": {"output": str(card.get("summary", ""))}}
                block = [Paragraph(title[:120], heading_style), *_render_card(response=response, body_style=body_style)]
                story.append(KeepTogether(block[:2]))
                story.extend(block[2:])
                story.append(Spacer(1, 18))

        def _make_canvas(*args: Any, **kwargs: Any) -> _BrandedCanvas:
            return _BrandedCanvas(*args, doc_title=payload.title[:70], **kwargs)

        doc.build(story, canvasmaker=_make_canvas)
        stem = sanitize_filename(payload.title, default="insightiq_export")
        return ExportResult(
            filename=f"{stem}.pdf",
            media_type="application/pdf",
            data=buffer.getvalue(),
        )


def _cover_story(payload: ExportPayload) -> list[Any]:
    styles = getSampleStyleSheet()
    wordmark_style = ParagraphStyle(
        "Wordmark", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=28, textColor=BRAND_PRIMARY
    )
    kicker_style = ParagraphStyle(
        "Kicker",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=BRAND_MUTED,
        spaceBefore=48,
    )
    title_style = ParagraphStyle(
        "CoverTitle", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=26, textColor=BRAND_DARK, leading=32, spaceBefore=10
    )
    meta_style = ParagraphStyle("CoverMeta", parent=styles["Normal"], fontName="Helvetica", fontSize=11, textColor=BRAND_MUTED, spaceBefore=18)

    kind_label = "Conversation Export" if payload.content_type == "conversation" else "Dashboard Report"
    generated = datetime.now(UTC).strftime("%B %d, %Y at %H:%M UTC")

    story: list[Any] = [
        Spacer(1, 40),
        Paragraph("InsightIQ", wordmark_style),
        Paragraph(kind_label.upper(), kicker_style),
        Paragraph(payload.title[:140], title_style),
        Paragraph(f"Generated {generated}", meta_style),
    ]

    active_filters = {k: v for k, v in (payload.data.get("filters") or {}).items() if v}
    if active_filters:
        filter_text = " &nbsp;\u2022&nbsp; ".join(f"<b>{k}</b>: {v}" for k, v in active_filters.items())
        story.append(Paragraph(f"Filters applied: {filter_text}", meta_style))

    card_count = len(payload.data.get("cards", []) or payload.data.get("messages", []))
    if card_count:
        noun = "card" if payload.content_type != "conversation" else "message"
        story.append(Paragraph(f"{card_count} {noun}{'s' if card_count != 1 else ''} included", meta_style))

    story.append(Spacer(1, 260))
    footer_style = ParagraphStyle("CoverFooter", parent=styles["Normal"], fontName="Helvetica", fontSize=9, textColor=BRAND_MUTED)
    story.append(Paragraph("This report was generated automatically by InsightIQ. Contents are confidential.", footer_style))
    return story


def _render_card(*, response: dict[str, Any], body_style: ParagraphStyle) -> list[Any]:
    blocks: list[Any] = []

    sub_panels = iter_sub_panels(response)
    if sub_panels is not None:
        styles = getSampleStyleSheet()
        sub_heading = ParagraphStyle(
            "SubHeading", parent=styles["Heading3"], fontName="Helvetica-Bold", fontSize=11, textColor=BRAND_DARK, spaceBefore=8, spaceAfter=4
        )
        if not sub_panels:
            blocks.append(Paragraph("No panels", body_style))
        for panel in sub_panels:
            panel_title = str(panel.get("title") or panel.get("response_type", "Panel"))
            blocks.append(Paragraph(panel_title[:120], sub_heading))
            blocks.extend(_render_card(response=panel, body_style=body_style))
        return blocks

    chart = response_chart_spec(response)
    if chart:
        blocks.append(_render_chart_drawing(chart))
        blocks.append(Spacer(1, 8))
        return blocks

    scatter = response_scatter_spec(response)
    if scatter:
        blocks.append(_render_scatter_drawing(scatter))
        blocks.append(Spacer(1, 8))
        return blocks

    matrix = response_table_matrix(response)
    if matrix:
        blocks.append(_render_table(matrix))
        return blocks

    rtype = str(response.get("response_type", ""))
    data = response.get("data") or {}

    if rtype == "kpi_card":
        label = str(data.get("label", "Value"))
        value = str(data.get("value", ""))
        kpi_style = ParagraphStyle(
            "Kpi", parent=body_style, fontSize=22, leading=28, textColor=BRAND_PRIMARY, fontName="Helvetica-Bold", spaceAfter=2
        )
        blocks.append(Paragraph(value, kpi_style))
        blocks.append(Paragraph(label, body_style))
        return blocks

    text = format_response_text(response)
    blocks.extend(_paragraph_lines(text, body_style))
    return blocks


def _render_table(matrix: list[list[str]]) -> Table:
    usable_width = PAGE_W - 2 * MARGIN
    col_count = max(len(matrix[0]), 1)
    col_width = usable_width / col_count
    table = Table(matrix, repeatRows=1, colWidths=[col_width] * col_count)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), BRAND_DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("GRID", (0, 0), (-1, -1), 0.4, BRAND_BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_SURFACE]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return table


def _render_chart_drawing(spec: dict[str, Any]) -> Drawing:
    width, height = 440, 240
    drawing = Drawing(width, height)
    kind = spec["kind"]
    labels = spec["labels"][:12]
    values = spec["values"][:12]

    if kind == "pie":
        pie = Pie()
        pie.x, pie.y = 150, 30
        pie.width = pie.height = 170
        pie.data = values
        pie.labels = [f"{lbl[:14]}" for lbl in labels]
        pie.simpleLabels = False
        pie.sideLabels = True
        for i in range(len(values)):
            pie.slices[i].fillColor = CHART_PALETTE[i % len(CHART_PALETTE)]
            pie.slices[i].strokeColor = colors.white
            pie.slices[i].strokeWidth = 1
        drawing.add(pie)
        return drawing

    if kind == "line":
        chart = HorizontalLineChart()
        chart.x, chart.y = 50, 30
        chart.width, chart.height = width - 90, height - 70
        chart.data = [values]
        chart.categoryAxis.categoryNames = [lbl[:10] for lbl in labels]
        chart.categoryAxis.labels.angle = 30
        chart.categoryAxis.labels.dy = -12
        chart.valueAxis.valueMin = min(0, min(values))
        chart.lines[0].strokeColor = BRAND_PRIMARY
        chart.lines[0].strokeWidth = 2
        chart.lineLabelFormat = "%d"
        drawing.add(chart)
        return drawing

    chart = VerticalBarChart()
    chart.x, chart.y = 50, 30
    chart.width, chart.height = width - 90, height - 70
    chart.data = [values]
    chart.categoryAxis.categoryNames = [lbl[:10] for lbl in labels]
    chart.categoryAxis.labels.angle = 30
    chart.categoryAxis.labels.dy = -12
    chart.categoryAxis.labels.fontSize = 7.5
    chart.valueAxis.valueMin = min(0, min(values))
    chart.bars[0].fillColor = BRAND_PRIMARY
    chart.barWidth = 10
    drawing.add(chart)
    return drawing


def _render_scatter_drawing(spec: dict[str, Any]) -> Drawing:
    from reportlab.graphics.charts.lineplots import ScatterPlot
    from reportlab.graphics.widgets.markers import makeMarker

    points = spec["points"][:200]
    width, height = 440, 240
    drawing = Drawing(width, height)
    plot = ScatterPlot()
    plot.x, plot.y = 55, 30
    plot.width, plot.height = width - 100, height - 60
    plot.data = [points]
    plot.xLabel = ""
    plot.yLabel = ""
    plot.lineLabelFormat = None
    plot.lines[0].symbol = makeMarker("FilledCircle")
    plot.lines[0].symbol.fillColor = BRAND_PRIMARY
    plot.lines[0].symbol.strokeColor = BRAND_PRIMARY
    plot.lines[0].symbol.size = 5
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x_pad = max((max(xs) - min(xs)) * 0.1, 1)
    y_pad = max((max(ys) - min(ys)) * 0.1, 1)
    plot.xValueAxis.valueMin = min(xs) - x_pad
    plot.xValueAxis.valueMax = max(xs) + x_pad
    plot.yValueAxis.valueMin = min(ys) - y_pad
    plot.yValueAxis.valueMax = max(ys) + y_pad
    drawing.add(plot)
    return drawing


def _paragraph_lines(text: str, style: ParagraphStyle) -> list[Any]:
    lines: list[Any] = []
    for raw in text.splitlines() or [""]:
        safe = raw.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.append(Paragraph(safe or "&nbsp;", style))
    return lines
